# ========== Profile ========== #
# avatar
#avatar: 'https://dn-maxfunweb.qbox.me/image640.jpeg'
avatar: 'https://avatars1.githubusercontent.com/u/6448929?s=400&v=4'
# author name
author: Dongamp
# signature
signature: 
# SNS
social:
  email: dongamp1990@gmail.com
  github: https://github.com/dongamp1990
  # wechat and qq should be a path of qr-code image
  #wechat: /assets/example_qr.png
  qq: 
  weibo: 
  zhihu: 
  douban: 
  facebook: 
  twitter: 
  instagram: 
  stack-overflow: 
  v2ex: 
  bilibili: 
  linkedin: 
  others: 
  rss: 
# friends
friends:
  #friendA: //www.baidu.com
  #friendB: //www.google.com
  #friendC: 
about:
  enable: false
  image: '/intro/about-bg.jpg'

# ========== Site ========== #
# title of the site
SEO_title: Dongamp
# main title
main_title: Dongamp blog
# subtitle
subtitle: keep learn
# site haeder image
site_header_image: 'http://oo12ugek5.bkt.clouddn.com/blog/images/banner.jpeg'
# post haeder image
post_header_image: 'https://dn-maxfunweb.qbox.me/imagepost-bg.jpg'
# 404 image
_404_image: '/intro/404-bg.jpg'

# ========== Comment ========== #
# Fill in the field to enable the corresponding comment plugin
# If you want to add other comment plugin, edit in "custom.ejs"
comment:
  # Livere  site: https://livere.com/
  livere_uid: 
  # Disqus  site: https://disqus.com/
  disqus_shortname: 
  # Changyan  site: http://changyan.kuaizhan.com/
  changyan_appid: 
  changyan_conf: 
  # Gitment  site: https://github.com/imsun/gitment
  gitment_owner: 
  gitment_repo: 
  gitment_client_id: 
  gitment_client_secret: 
  # Youyan  site: http://www.uyan.cc/
  youyan_uid: 

# ========== Analytics ========== #
# Busuanzi pv analytics
busuanzi: true
# Baidu analytics
baidu_analytics: 
# Google analytics
google_analytics: 
# CNZZ analytics
CNZZ_analytics: 

# ========== Others ========== #
# favicon
favicon: /assets/favicon.ico
# truncate length of abstracts in index page (the default is 300, there will be no abstruct if you input 0)
truncate_length: 100
# enable toc
toc: true
# intro height (the default is 50 percents of the screen, you can input other number)
index_intro_height: 30
post_intro_height: 30
about_intro_height: 30
# copyright
copyright:
  enable: false
  # https://creativecommons.org/
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
